name: Build Image

on:
 push:
  paths:
    - 'alpine/**'
    - 'debian/**'
  pull_request:
    paths:
    - 'alpine/**'
    - 'debian/**'
  schedule:
    - cron: '0 6 * * *'

env:
  IMAGE: "docker.io/sqlops/draw.io"
  VERSION_FILE: "./drawio/VERSION"

jobs:
  build-image:
    name: "Building ${{ matrix.drawio }} base image"
    strategy:
      matrix:
        drawio:
          - debian
          - alpine
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Set ENV variables
        run: |
          cat ${{ env.VERSION_FILE }} >> $GITHUB_ENV
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.IMAGE }}:${{ env.VERSION }}-${{ matrix.drawio }},${{ env.IMAGE }}:${{ matrix.drawio }}
          context: ${{ matrix.drawio }}/
          file: ${{ matrix.drawio }}/Dockerfile
          platforms: linux/amd64
          load: True
      
      - name: Test webapp
        run: |
          docker run --name 'drawio' -d ${{ env.IMAGE }}:${{ env.VERSION }}-${{ matrix.drawio }}
          sleep 10
          docker exec drawio /bin/bash -c "curl -i http://localhost:8080"

      - name: Push image
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.IMAGE }}:${{ env.VERSION }}-${{ matrix.drawio }},${{ env.IMAGE }}:${{ matrix.drawio }}
          context: ${{ matrix.drawio }}/
          file: ${{ matrix.drawio }}/Dockerfile
          platforms: linux/amd64
          push: True